"""create symbol and exchange tables

Revision ID: 82096b709f10
Revises: 
Create Date: 2021-05-02 16:07:53.141537

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "82096b709f10"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange",
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("mic", sa.String(), nullable=True),
        sa.Column("exchange_suffix", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("exchange"),
    )
    op.create_table(
        "us_exchange",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("long_name", sa.String(), nullable=True),
        sa.Column("mic", sa.String(), nullable=True),
        sa.Column("tape_id", sa.String(), nullable=True),
        sa.Column("oats_id", sa.String(), nullable=True),
        sa.Column("ref_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "symbol",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("exchange_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("iex_id", sa.String(), nullable=True),
        sa.Column("figi", sa.String(), nullable=True),
        sa.Column("cik", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("ad", "cs", "cef", "et", "oef", "ps", "rt", "struct", "ut", "wi", "wt", name="symbol_type"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchange.exchange"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("symbol")
    op.drop_table("us_exchange")
    op.drop_table("exchange")
    # ### end Alembic commands ###
