name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Cache poetry install
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install dependencies
        run: poetry install

      - name: Black
        run: poetry run black --check .

      - name: Isort
        run: poetry run isort --check .

      - name: Mypy
        run:  poetry run mypy financial_data --config-file mypy.ini

      - name: Test
        run: poetry run pytest -v --durations=0

