name: main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-action
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4

      - name: Cache poetry install
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Install dependencies
        run: poetry install

      - name: Format
        run: |
          poetry run black --check .
          poetry run isort --check .

      - name: Test
        run: poetry run pytest -v --durations=0

